# Changes here will be overwritten by Copier
_commit: 0ddd376
_src_path: ../../templates/base
add_extension: python
email: t.paine154@gmail.com
github: airflow-laminar
project_description: Priority Tags for Airflow Dags
project_name: airflow-priority
python_version_primary: '3.11'
team: the airflow-priority authors
